name: "Terraform GitOps (Controle Manual)"

on:
  pull_request:
    branches:
      - main
  # Isso cria o botão no GitHub Actions!
  workflow_dispatch:
    inputs:
      tf_action:
        description: 'Qual ação você deseja executar?'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  # --- Credenciais de Acesso OCI ---
  TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
  TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
  TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
  TF_VAR_region: ${{ secrets.OCI_REGION }}
  
  # Nota sobre a chave: No pipeline usamos o conteúdo (private_key) e não o caminho (private_key_path)
  TF_VAR_private_key_path: "private_key.pem"

  # --- Credenciais do Backend S3 ---
  AWS_ACCESS_KEY_ID: ${{ secrets.OCI_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.OCI_S3_SECRET_KEY }}

  # --- Variáveis da Infraestrutura (O que faltava!) ---
  TF_VAR_compartment_id: ${{ secrets.OCI_COMPARTMENT_OCID }}
  TF_VAR_subnet_id: ${{ secrets.OCI_SUBNET_ID }}
  TF_VAR_image_id: ${{ secrets.OCI_IMAGE_ID }}

jobs:
  terraform:
    name: "Execução do Terraform"
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: 📥 Checkout do Codigo
        uses: actions/checkout@v4

      - name: 📝 Criar arquivo da Private Key
        run: |
          echo "$OCI_KEY" > private_key.pem
          chmod 600 private_key.pem
        env:
          OCI_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
      - name: 🛠️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.7"
        
     
      - name: ⚙️ Terraform Init
        id: init
        run: terraform init

      - name: 📋 Terraform Plan
        # Roda se for Pull Request OU se escolher 'plan' no botão manual
        if: github.event_name == 'pull_request' || github.event.inputs.tf_action == 'plan'
        run: terraform plan -no-color

      - name: 🚀 Terraform Apply
        # Roda APENAS se escolher 'apply' no botão manual
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tf_action == 'apply'
        run: terraform apply -auto-approve -no-color

      - name: 💣 Terraform Destroy
        # Roda APENAS se escolher 'destroy' no botão manual
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tf_action == 'destroy'
        run: terraform destroy -auto-approve -no-color